version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - clippy
  - Deque
  - dtolnay
  - flate2
  - indexmap
  - Interner
  - Justfile
  - keywork
  - krox
  - miette
  - mockall
  - proptest
  - reqwest
  - rstest
  - serde
  - subtyping
  - sysinfo
  - thiserror
  - walkdir
ignoreWords: []
import: []
