version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - clippy
  - cpus
  - dashmap
  - Deque
  - Dhall
  - dtolnay
  - flate2
  - Furlanetto
  - indexmap
  - Interner
  - Justfile
  - keywork
  - krox
  - miette
  - mockall
  - proptest
  - reqwest
  - rstest
  - scrutinee
  - serde
  - stdlib
  - subtyping
  - sysinfo
  - thiserror
  - usize
  - walkdir
ignoreWords: []
import: []
